config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/pages/profile', to: 'pages#profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :destroy]
  # add index??
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :occupancy, presence: true

  has_many :bookings
  belongs_to :user

  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :booked_flats, through: :bookings, source: :flats
  has_many :flats, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @flat = Flat.find(params[:flat_id])

    @booking.user = current_user
    @booking.flat = @flat
    @booking.user_id?
    if @booking.save
      redirect_to pages_profile_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to pages_profile_path
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :flat_id, :date_from, :date_to, :guests)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all

    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        infoWindow: render_to_string(partial: "/flats/info_window", locals: { flat: flat }),
        # image_url: helpers.asset_url('assets/images/city_lights.jpg')
      }
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to pages_profile_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
  end

  def destroy
    @flat.destroy
    redirect_to pages_profile_path
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to pages_profile_path
    else
      render :edit
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :occupancy, :photo, :user_id)
  end

  def set_flat
      @flat = Flat.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home; end

  def profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class = "profile-banner">
  <h1>Make a booking</h1>
</div>
<div class="form-container" style="padding: 50px 0px">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8 d-flex form show-card-img">
        <%= cl_image_tag @flat.photo.key %>
      </div>
      <div class="col-6 col-md-4 d-flex form">
        <%= simple_form_for [@flat, @booking] do |f| %>
          <div class="form-inputs">
            <%= f.input :date_from %>
            <%= f.input :date_to %>
            <%= f.input :guests %>
            <%= f.submit(class: 'standard-button')%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/_info_window.html.erb
<%= cl_image_tag flat.photo.key, height: 100, crop: :fill %>

<h5><%= link_to "#{flat.name}", flat_path(flat) %></h5>
<p><%= flat.address %></p>

app/views/flats/edit.html.erb
<div class = "profile-banner">
  <h1>Edit <%= @flat.name %></h1>
</div>
<div class="form-container">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8 d-flex form show-card-img" style="align-self: center">
        <%= cl_image_tag @flat.photo.key %>
      </div>
      <div class="col-6 col-md-4 d-flex form">
        <%= simple_form_for @flat do |f| %>
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :occupancy %>
          <%= f.submit(class: 'standard-button') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class = "profile-banner">
  <div class = "container">
    <h1 class="flat-heading"> Available Flats </h1>
  </div>
</div>

<!-- <h1 class="flat_heading">Search Flats</h1> -->

<div id="map"
   style="width: 100%; height: 300px; margin-top: 32px; margin-bottom: 24px;"
   data-markers="<%= @markers.to_json %>"
   data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<section class="container-custom">

 <% @flats.each do |flat| %>
  <div class="card col-lg-12 col-sm-6 mx-auto" style="width: 24rem;">
    <!-- <a href="link_to 'Flat Details', flat_path(flat)"> -->
    <%= cl_image_tag flat.photo.key, height: 300, crop: :fill %>

    <div class="card-body">
      <p class="card-title"> <%= flat.name %> <br>
      <p>
      <%= flat.address %> <br>
      </p>
      <%= link_to "Flat Details", flat_path(flat), class: "standard-button" %>
    </div>
<!-- </a> -->
  </div>
  <% end %>
</section>

app/views/flats/new.html.erb
<div class = "profile-banner">
  <h1>Add a new property</h1>
</div>
<div class="form-container">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8 form">
        <%= simple_form_for @flat do |f| %>

            <%= f.input :name %>
            <%= f.input :address %>
            <%= f.input :description %>
            <%= f.input :occupancy %>
            <%= f.input :photo, as: :file %>
            <% if current_user %>
            <%= f.hidden_field :user_id, value: current_user.id%>
            <% end %>
            <%= f.submit(class: 'standard-button')%>

          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class = "profile-banner">
  <div class = "container">
  </div>
</div>


<div class = "container">
  <div class = "show-card">
    <div class = "show-card-img">
      <%= cl_image_tag @flat.photo.key %>
    </div>
    <div class = "show-card-desc">
      <div>
        <h3> <%= @flat.name %> </h3>
        <p> <%= @flat.address %> <br>
        <%= @flat.description %> <br>
        Sleeps <%= @flat.occupancy %>
        </p>
        <%= link_to 'New Booking',  new_flat_booking_path(@flat), class: "standard-button" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright &copy; <%= Time.now.year %> Air-Turn-Up
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "home.png", alt: "House" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "View all flats", flats_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "greta.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to 'View profile', pages_profile_path, class: "dropdown-item" %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBnBCloneTurnUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <!-- nav bar -->
    <%= render 'layouts/header' %>
    <section class="main">
      <%= yield %>
    </section>
    
    <!-- devise alerts -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Welcome to AirTurn Up</h1>
    <p>Find the best flats</p>
    <%= link_to "Search flats", flats_path, class: "home-button" %>
  </div>
</div>

app/views/pages/profile.html.erb
<div class = "profile-banner">
  <div class = "container">
    <h1><%= @user.first_name %> <%= @user.last_name %></h1>
  </div>
</div>

<div class = "container">
  <div class = "profile-content">
    <div class = "profile-card">
      <h2>My Bookings</h2>
      <% @user.bookings.each do |booking| %>
        <div class = "profile-flat-card">
          <%= cl_image_tag booking.flat.photo.key, height: 150, width: 150, crop: :fill %>
          <div class = "profile-flat-card-desc">
            <p><strong><%= booking.flat.name %></strong></p>
            <p>booked from:</p>
            <p><%= booking.date_from %> to <%= booking.date_to %></p>
            <p>for <%= booking.guests %> guests</p>
             <%= link_to  "Delete Booking", booking_path(booking), class: 'small-button',
                method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <% end %>
    </div>

    <div class = "profile-card">
      <h2>My Flats</h2>
      <% @user.flats.each do |flat| %>
        <div class = "profile-flat-card">
          <%= cl_image_tag flat.photo.key, height: 150, width: 150, crop: :fill %>
          <div class = "profile-flat-card-desc">
            <p><strong><%= flat.name %></strong></p>
            <p><%= flat.address %></p>
            <p>Listed occupancy: <%= flat.occupancy %></p>
            <%= link_to 'Edit Flat', edit_flat_path(flat), class: 'small-button' %>
            <%= link_to  "Delete", flat_path(flat), class: 'small-button',
                method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <% end %>
      <%= link_to 'Create new listing', new_flat_path, class: "standard-button" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do
    <%= image_tag "home.png", alt: "House" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <%= link_to 'View profile', pages_profile_path, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div> %>



<!--
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <a class="navbar-brand" href="#">

      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Sign out</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
        </ul>
      </div>
    </div> -->